### ISSUE TITLE
打算就业？NLP方向的工程师嘛，好像也还可以

### ISSUE THREAD

**Issue by Yemaoxin** [hioujinnsenn/hioujinnsenn.github.io#1]

**Comment by hioujinnsenn** [comment]
嗯嗯，确实




绯樱尘染
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hioujinnsenn/hioujinnsenn.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月30日(星期四) 下午3:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[hioujinnsenn/hioujinnsenn.github.io] 打算就业？NLP方向的工程师嘛，好像也还可以 (Issue #1)

**Comment by Yemaoxin** [comment]
唔，没有准备读博嘛？或者考公、选调？感觉武大硕士选调也不错呀？武汉或者宜昌的话，感觉自己对大厂就业没什么兴趣。后面感觉可能顺利的话也许继续读博，或者考公或者选调把，现在倒是有参加福建省选调的资格。

**Comment by hioujinnsenn** [comment]
奥，谢谢你的关心，不过不准备继续深造了，想直接工作吧，志向也不在公务员这种。你要是想读博也挺好，就是这条路估计不容易。考公选调确实也是不错的选择。加油吧。
&nbsp;


绯樱尘染
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月30日(星期四) 下午3:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hioujinnsenn/hioujinnsenn.github.io] 打算就业？NLP方向的工程师嘛，好像也还可以 (Issue #1)





 
唔，没有准备读博嘛？或者考公、选调？感觉武大硕士选调也不错呀？武汉或者宜昌的话，感觉自己对大厂就业没什么兴趣。后面感觉可能顺利的话也许继续读博，或者考公或者选调把，现在倒是有参加福建省选调的资格。

**Comment by Yemaoxin** [comment]
哈哈哈，好的，看看吧，就业什么的也不太担心，我们搞存储的，感觉还可以
